from setuptools import setup, find_packages

setup(
    name="llama3.2_token_counter",
    version="0.1.0",
    packages=find_packages(),
    include_package_data=True,
    package_data={"llama_token_counter": ["tokenizer_config.json"]},
    install_requires=["transformers", "regex"],
    author="anthoeknee",
    author_email="pacyheb@protonmail.com",
    description="A simple token counter for Llama 3.2 models.",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/anthoeknee/llama_token_counter",
    project_urls={
        "Bug Tracker": "https://github.com/anthoeknee/llama_token_counter/issues",
        "Source Code": "https://github.com/anthoeknee/llama_token_counter",
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Text Processing :: Linguistic",
    ],
    license_files=["LICENSE"],
    python_requires=">=3.7",
)